export default {
  'poppins-900': require('../assets/fonts/Poppins-Black.ttf'),
  'poppins-900-italic': require('../assets/fonts/Poppins-BlackItalic.ttf'),
  'poppins-800': require('../assets/fonts/Poppins-ExtraBold.ttf'),
  'poppins-800-italic': require('../assets/fonts/Poppins-ExtraBoldItalic.ttf'),
  'poppins-bold': require('../assets/fonts/Poppins-Bold.ttf'),
  'poppins-bold-italic': require('../assets/fonts/Poppins-BoldItalic.ttf'),
  'poppins-600': require('../assets/fonts/Poppins-SemiBold.ttf'),
  'poppins-600-italic': require('../assets/fonts/Poppins-SemiBoldItalic.ttf'),
  'poppins-medium': require('../assets/fonts/Poppins-Medium.ttf'),
  'poppins-medium-italic': require('../assets/fonts/Poppins-MediumItalic.ttf'),
  'poppins-regular': require('../assets/fonts/Poppins-Regular.ttf'),
  'poppins-regular-italic': require('../assets/fonts/Poppins-Italic.ttf'),
  'poppins-light': require('../assets/fonts/Poppins-Light.ttf'),
  'poppins-light-italic': require('../assets/fonts/Poppins-LightItalic.ttf'),
  'poppins-200': require('../assets/fonts/Poppins-ExtraLight.ttf'),
  'poppins-200-italic': require('../assets/fonts/Poppins-ExtraLightItalic.ttf'),
  'poppins-thin': require('../assets/fonts/Poppins-Thin.ttf'),
  'poppins-thin-italic': require('../assets/fonts/Poppins-ThinItalic.ttf'),
};
